language: node_js

node_js: stable

branches:
  only:
  - dev

before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli

install:
- npm install

script:
- git submodule init
- git submodule update    #   用于更新主题,更新源为自己的主题项目，否则会clone最新NexT主题，而官方主题配置文件没有设置
- hexo clean   
- hexo g

after_success:
- git config --global user.name "xin053"
- git config --global user.email "13207130066.cool@163.com"
- sed -i'' "s~git@github.com:xin053/xin053.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/xin053/xin053.github.io.git~" _config.yml
- hexo deploy