language: node_js

node_js: stable

branches:
  only:
  - master

before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli

install:
- npm install

script:
- git submodule init      # 用于更新主题
- git submodule update
- hexo clean && hexo g

after_success:
- git config --global user.name "xin053"
- git config --global user.email "13207130066.cool@163.com"
- sed -i'' "/^ *repo/s~github\.com~<${GH_TOKEN}>@github.com~" _config.yml
- hexo deploy